baseURL = 'https://photography.twaslowski.com/'
locale = 'en-us'
title = "Tobi Travels"
theme = 'newsroom'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[params]
  umami_website_id = '207ccaf6-7a13-4b1f-85a3-1f86fc94174a'
  imageBaseURL = 'https://img.twaslowski.com/file/'
  subtitle = 'A photography and travel blog'
  telegram_bot = 'tobi_newsletter_bot'
  buttondown_username = 'twaslowski'
  [params.contact]
    email = 'contact@twaslowski.com'

[markup.goldmark.renderer]
  unsafe = true
