baseURL = 'https://photography.twaslowski.com/'
locale = 'en-us'
title = "Tobi Travels"
theme = 'newsroom'

[params]
  imageBaseURL = 'https://img.twaslowski.com/file/photos-web-prod/'
  subtitle = 'A photography and travel blog'
  [params.contact]
    email = 'contact@twaslowski.com'