version: "3"
tasks:
  run:
    desc: Run hugo server, including drafts
    cmd: hugo server -D

  tf:
    desc: Apply infrastructure changes
    dir: terraform
    dotenv:
      - .env
    cmd: terraform apply -var-file=config/prod.tfvars

  sync:
    desc: Sync images to remote storages
    dir: images
    cmd: rclone sync . b2:photos-web-prod --progress

  browse:
    desc: Explore images directory; opens Finder on macOS
    dir: images
    cmd: open .