version: "3"
tasks:
  run:
    desc: Run hugo server, including drafts
    cmd: hugo server -D

  build:
    desc: Run hugo server, including drafts
    cmd: hugo --gc --minify --baseURL https://photography.twaslowski.com

  sync:
    desc: Sync images to remote storages
    dir: images
    cmd: rclone sync . b2:photos-web-prod --progress

  copy:*:
    desc: Copy directory to remote storage
    vars:
      SUBDIR: '{{index .MATCH 0}}'
    cmd: rclone copy ./images/{{.SUBDIR}}/ b2:photos-web-prod --progress

  resize:*:
    desc: Resize images to different outputs for optimized loading
    vars:
      SUBDIR: '{{index .MATCH 0}}'
    cmds:
      - ./scripts/resize-images.sh ./images/{{.SUBDIR}}

  browse:
    desc: Explore images directory; opens Finder on macOS
    dir: images
    cmd: open .

  apply:*:
    desc: Apply infrastructure changes
    vars:
      dir: '{{index .MATCH 0}}'
    dir: terraform/{{.dir}}
    dotenv:
      - .env
    cmds:
      - terraform apply -var-file=config/prod.tfvars

  get-env:
    desc: Get environment variables from 1password CLI
    cmds:
      - op environment read ab2qga4a3pvvkk46pgqpu4oway
